data:
  train_dataset_path: 'dataset/training_data.csv'
  test_dataset_path: 'dataset/test_data.csv'
  store_dataset_path: 'dataset/outlet_info.csv'

data_prep:
  is_feature_scaling: True
  scaler_output_path: 'src/utils/feature_scaler.pkl'
  
model:
  is_model_selection: True
  is_hp_tuning : True
  is_feature_importance_analysis : True
  is_model_evaluation: True
  output_path: 'src/models/quantity_forecast_model.pkl'

